language: python
dist: xenial # Fix for wrong sqlite version.
install:
  - pip install -r requirements.txt
  - pip install python-coveralls
  - pip install coverage
script:
  - coverage run --include="web/*","app/*"  manage.py test web  
after_success:
  - coveralls
