# Generated by Django 2.2 on 2019-05-14 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bloodtype',
            field=models.SmallIntegerField(blank=True, choices=[(0, '0'), (1, 'A'), (2, 'B'), (3, 'AB')], null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Male'), (1, 'Female'), (2, 'Diverse')], null=True),
        ),
    ]
