# Generated by Django 2.2 on 2019-05-22 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20190521_2305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donationplace',
            name='publish',
        ),
        migrations.AddField(
            model_name='donationplace',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
