# Generated by Django 2.2 on 2019-05-28 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20190522_1340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='time',
            new_name='donationdate',
        ),
    ]
