# Generated by Django 2.2.2 on 2019-06-12 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationplace',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
