# Generated by Django 2.2.2 on 2019-06-12 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_auto_20190612_2215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='donationdate',
            new_name='date',
        ),
    ]
