# Generated by Django 2.2.2 on 2019-06-14 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_auto_20190612_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='get_notified',
            field=models.BooleanField(default=False),
        ),
    ]
