# Generated by Django 2.2.2 on 2019-06-14 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_profile_get_notified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='get_notified',
            new_name='got_notified',
        ),
    ]
